Added a redirect link to a new tab Fixes #22
CircuitVerse/CircuitVerse-Presentation-Embed pull request #28
Opened 2021-11-23 20:33 UTC by Palaksharma23

Fixes #22

I have redirected link to a new tab 

https://user-images.githubusercontent.com/87171452/143100989-f9e56c2a-330a-4f63-8c9d-38e06f6520e2.mp4

2021-11-23 20:33 UTC, Palaksharma23 commented
@manjotsidhu @Shivansh2407 can you please once review my pull request  .

2021-11-28 05:20 UTC, Palaksharma23 commented
@Shivansh2407 @manjotsidhu can you please once review my pull request

2021-11-28 05:39 UTC, manjotsidhu requested changes

2021-11-28 05:39 UTC, manjotsidhu commented on Chrome Extension/views/browser_action.html
> +	This extension will now load live circuits in Google Slides. Make sure to install Google Slides Add-On as well. For more details, read the user documentation <a href="https://docs.circuitverse.org/#
```suggestion
	This extension will now load live circuits in Google Slides. Make sure to install Google Slides Add-On as well. For more details, read the user documentation <a href="https://docs.circuitverse.org/#/embedding_circuits?id=embedding-in-google-slides" target="_blank">here</a>.
```

2021-11-30 16:06 UTC, Palaksharma23 commented
done  :)

2021-11-30 16:19 UTC, manjotsidhu approved these changes

2021-12-08 17:45 UTC, merged